### ISSUE TITLE
Обновить списки

### ISSUE THREAD

**Issue by derlaft** [TTLMaster/yota-ban-list#1]
Текущие проблемы (судя по ветке форума):
- Некоторые адреса Google Play и гуглокартинок в бане
- Нужно иметь копию списка с хостами, потому что ip-адреса постоянно изменяются
- Забанить Steam

**Comment by kolyanok** [comment]
Убрал лишние адреса, обновил IP.
Со Стимом лично у меня никаких проблем выявлено не было. Спрашивал в теме обхода ограничений на 4PDA — тоже никто не отписался. Так что пока блокировать его я не вижу особого смысла.

**Comment by x785** [comment]
apps.corel.com 
corel.com 
apps.corel.com

**Comment by iiiypuk** [comment]
Нате
http://pastebin.com/raw/hHqLA8ss

**Comment by LionZXY** [comment]
Предлагаю сделать автообновление через Travis по Cron'у. Сегодня все скрипты и конфигурации напишу, надо только включить травис для этого репозитория

**Comment by x785** [comment]
В опенврт необходимо будет делать какие либо изменения?

10 июня 2017 г., 11:45 пользователь LionZXY <notifications@github.com>
написал:

**Comment by LionZXY** [comment]
Не обязательно. Можно написать скрипт update.sh, который добавляет адреса из pastebin, который сверху.
Ещё можно добавить скрипт check.sh, который будет проверять итоговый файл на валидность (мало ли что)

**Comment by x785** [comment]
Было бы не плохо гдето увидеть эти скрипты.

10 июня 2017 г., 13:26 пользователь LionZXY <notifications@github.com>
написал:

**Comment by LionZXY** [comment]
Соответственно как выглядит крон:
- Загружаем pastebin
- Парсим
- Объединяем со старым списком
- Перебираем все домены и смотрим IP
- Проверяем есть ли локалхост IP и прочая невалидная гадость
- Если проверка прошла, пушим на гитхаб

**Comment by derlaft** [comment]
@LionZXY сделал, но без проверки на локахост и невалидную гадость. Если есть уже готовый код, можешь поделиться

**Comment by LionZXY** [comment]
Нет, нету :) Планировал на выходных этим заняться. Спасибо тебе за репозиторий и скрипты.

**Comment by a13** [comment]
@derlaft 

тебя отдельные ветки заводить не учили?

**Comment by dima333750** [comment]
Начиная с 05.10.17, начала активно палить по chrome, вот примерный список:
127.0.0.1 ssl.gstatic.com
127.0.0.1 docs.google.com
127.0.0.1 notifications.google.com
127.0.0.1 play.google.com
127.0.0.1 sb-ssl.google.com
127.0.0.1 mtalk.google.com
127.0.0.1 pki.google.com
127.0.0.1 apis.google.com
127.0.0.1 *.googleapis.com
К сожаление отключает встроенный переводчик(

**Comment by kolyanok** [comment]
@dima333750 это нельзя. Там и Гугл плей, и Гугл докс.
